spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112112
logging:
  level:
    com.fioriro: debug
  pattern:
    dateformat: HH:mm:ss
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
mybatis-plus:
  type-aliases-package: com.fioriro.mp.domain.po
  global-config:
    db-config:
      id-type: auto
  mapper-locations: "classpath*:/mapper/**/*.xml"
